---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify
  hosts: all
  gather_facts: true
  tasks:

    - name: Include OS/Version-specific variables
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
          paths:
            - ../../vars # Necessary to find files from molecule/default/
          skip: true

    - name: Get list of installed packages
      ansible.builtin.package_facts:
        manager: auto

    # --- Package Checks ---

    - name: Assert core scanner is installed
      ansible.builtin.assert:
        that:
          - "'openscap-scanner' in ansible_facts.packages"
        fail_msg: "openscap-scanner package was not found."
        quiet: true
      when: oscap_compliance_scan or oscap_oval_scan

    - name: Assert security guide package is installed
      ansible.builtin.assert:
        that:
          - "oscap_guide_package in ansible_facts.packages"
        fail_msg: "oscap_guide_package '{{ oscap_guide_package }}' was not found."
        quiet: true
      when: oscap_compliance_scan

    - name: Assert bzip2 is installed
      ansible.builtin.assert:
        that:
          - "'bzip2' in ansible_facts.packages"
        fail_msg: "bzip2 package was not found (required for OVAL scan)."
        quiet: true
      when: oscap_oval_scan

    # --- Compliance Report Check ---

    - name: Check for OSCAP compliance results files
      ansible.builtin.stat:
        path: "{{ item }}"
      register: oscap_compliance_reports
      loop:
        - /var/tmp/ospp-results.xml
        - /var/tmp/ospp-results.html
      when: oscap_compliance_scan

    - name: Assert OSCAP compliance results files exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
        fail_msg: "OSCAP compliance report file '{{ item.item }}' was not found."
        quiet: true
      loop: "{{ oscap_compliance_reports.results | default([]) }}"
      loop_control:
        label: "{{ item.item }}"
      when: oscap_compliance_scan

    # --- OVAL Report Check ---

    - name: Check for OSCAP OVAL results file
      ansible.builtin.stat:
        path: /var/tmp/oval-results.html
      register: oscap_oval_report
      when: oscap_oval_scan

    - name: Assert OSCAP OVAL results file exists
      ansible.builtin.assert:
        that:
          - oscap_oval_report.stat.exists
        fail_msg: "OSCAP OVAL report file '/var/tmp/oval-results.html' was not found."
        quiet: true
      when: oscap_oval_scan
